### ISSUE TITLE
404 x11-repo no longer has a release file

### ISSUE THREAD

**Issue by AmidBidee** [termux/x11-packages#198]
\Krummy🔰pkg install sdl2
      . . .
  404  Not Found
Err:9 https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://dl.bintray.com/xeffyr/unstable-packages-21 unstable Release' does no longer have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'https://dl.bintray.com/xeffyr/x11-packages-21 x11 Release' does no longer have  a release file

**Comment by xeffyr** [comment]
https://dl.bintray.com/xeffyr/x11-packages-21 will never have release file. It is **removed** - I no longer provide packages compiled for Android API level 21.

**Comment by Mishqutin** [comment]
What am I supposed to do then? Is it something with my system?

**Comment by xeffyr** [comment]
> What am I supposed to do then?

If your device running Android OS version 5.x or 6.x, then you cannot do anything. I no longer provide packages compatible with packages from https://termux.net which now is legacy (since 01.01.2020) and not supported.

**Comment by SIMMORSAL** [comment]
Can we know why?

**Comment by xeffyr** [comment]
@SIMMORSAL Why what? My account on Bintray was limited on disk space, moreover, since May 2021 Bintray no longer exists as service. Also, reminding: **we have dropped support of Android 5/6, no work (any kind: from bug fixes/updates to new mirrors) will be done on it anymore.**

If you really need X11 packages for legacy Termux, get full repository archive at https://archive.org/download/termux-repositories-legacy/termux-repositories-legacy-24.12.2019.tar (7 GB!) - there are all last available packages compatible with Android 5/6, including X11 packages.
