### ISSUE TITLE
Request video editor in x11 packages.

### ISSUE THREAD

**Issue by kcubeterm** [termux/x11-packages#202]
I apologise for not providing any package name , which i am requesting, because i really don't know which one will suitable for termux, i just requesting video editor gui,

**Comment by aaavvi** [comment]
hello dear i'm not able to stop vncserver

**Comment by cargocultprog** [comment]
Unlikely to happen. For a video editor, or even just a video player, you need a fancy GUI desktop with a lot of software. And, I do mean A LOT of software. Also, most Android devices do not have enough RAM to make it worthwhile, and there is no hard drive.

Even after installing a large system into Termux (Arch Linux ARM), video editing is virtually impossible. Part of the reason is that a number of Linux libraries make calls to memory in a way that SELinux (security) prohibits. This is vaguely related to the famous buffer overflow problems of years ago. Some of those libraries can be re-compiled to avoid the problem, but others would require a lot of reverse engineering in C programming, especially for obscure formats. Not worth it.

There are some video editor apps, native to Android, that can do a little editing. They work because they use the native Android GUI, and make use of native Android system calls.

If all you wish to do is command-line file editing, such as by adding or removing metadata (title, etc.) then I believe ffmpeg can do it, right now.

**Comment by kcubeterm** [comment]
Thankyou sir @cargocultprog

**Comment by kcubeterm** [comment]
I installed openshot in aarch Linux,but there is error of audio,since aarch has not audio driver which can interact with Android hardware.
