### ISSUE TITLE
sdl2-mixer sdl-mixer

### ISSUE THREAD

**Issue by strikersix23** [termux/x11-packages#207]
Required for alot of programs I'm trying to port.

Home:
https://www.libsdl.org/projects/SDL_mixer/

Source:
https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.4.tar.gz

**Comment by cargocultprog** [comment]
The sdl software can probably be compiled and work in Termux. It is available in Arch Linux ARM, which sits in Termux proot. You will need to configure it to work with PulseAudio, using the SL_ES modules. If Termux works with Alsa, I do not know how to do it. Note that certain audio libraries, particularly libmad and libmpeg2, must be specially compiled to avoid violating Android SELinux due to executable stack. It can be done. I do not know if this affects sdl.

**Comment by strikersix23** [comment]
I don't exactly need the executable I just need the headers and related dev files. In other words I just need a stub and actual headers

**Comment by strikersix23** [comment]
Also sdl is native on android so it shouldn't be an real issue plus these are in the Ndk if I'm correct

**Comment by xeffyr** [comment]
`sdl` and `sdl2` already available...

**Comment by strikersix23** [comment]
Yes they are I just want the sdl-mixer headers and libs

**Comment by xeffyr** [comment]
Package is now available.

Use this command to install it:
```
pkg install sdl-mixer
```

For SDL2:
```
pkg install sdl2-mixer
```
