### ISSUE TITLE
Package Request: Re-enable emacs-x

### ISSUE THREAD

**Issue by Qqwy** [termux/x11-packages#251]
I was very excited to learn that Termux supports running with an X-server, and that an emacs package supporting the GUI interface exists...

only to find out that it was disabled a couple of months ago because there were problems building it.
Would it be possible to try this again?
At least I hereby want to let you know that I would be an interested party to use `emacs-x`.

Thank you!

**Comment by etiago** [comment]
I had a quick look at this, and I think we might have better luck by targeting the latest emacs 27 version.

The non-X emacs in Termux runs on that version. I also found these patches that were needed to make it work: https://github.com/termux/termux-packages/pull/4622/files

I don't have enough time to look into this at the moment but it looks that it might not be impossible to achieve. Might just need someone who knows what they're doing to have a look at it... hint hint @Grimler91 :grimacing: :smile: 

I fully appreciate you might not have the time either, but just thought I'd mention it since you were the one who fixed the non-X package :slightly_smiling_face:

**Comment by Grimler91** [comment]
Hi, did not notice that I was tagged here. Problem is that I do not use x11 and vnc in my daily usage of termux so I would need to setup and install everything just for testing emacs-x, would be better if someone else looks into it.

Might work to just copy the package from the main repository and change the configure options and dependencies (and patches?) to match the disabled emacs-x package.

**Comment by cl4rknova** [comment]
Hi, I gave it a try and started compiling with emacs-27.2.
First steps are working and I already did some adjustments for the patches.
Anyway - compiling now fails with "arm-binfmt-P: Could not open '/system/bin/linker': No such file or directory"

This is about the android linker if I understand it right. Should that exist in the building environment?
Maybe someone could give me a hint...

**Comment by xeffyr** [comment]
@cl4rknova Your build should **never** attempt to execute something that has been cross-compiled.

Please take a look into https://github.com/termux/termux-packages/blob/d741daf94fb38b624a9bc37e554875f4d80a8362/packages/emacs/build.sh (no-x emacs) and relevant patches there: https://github.com/termux/termux-packages/tree/71fb6068d877ac80840e498dbb9c1a8561f5ee31/packages/emacs

If you look the commit message when it was disabled, you will find the exact issue: https://github.com/termux/x11-packages/commit/ffc77cf0d8dbd9f7da56428f5a2cda0b51d3a00c - nothing compilation related.

**Comment by cl4rknova** [comment]
@xeffyr Thank you. I now modified the emacs package instead of fiddling around with the emacs-x one and it works great, just add "--with-x" and jpeg/tiff/png support etc. Compiled without any problem.

**Comment by xeffyr** [comment]
Package will be available for installation shortly on packages.termux.org and within hours on mirrors.
