### ISSUE TITLE
Package request: Python-qt5

### ISSUE THREAD

**Issue by Neo-Oli** [termux/x11-packages#4]
Now that we have qt5-base it should be possible to build the python-bindings for it, right? Installing PyQt5 via pip is not possible for Termux, because it is only provided for 64 bit Linux and Windows. So it needs to be built from source. 

**Package description**
PyQt is a Python binding of the cross-platform GUI toolkit Qt,

**Link to home page and sources**
1. Home page: https://riverbankcomputing.com/software/pyqt/intro
2. Source code: https://www.riverbankcomputing.com/software/pyqt/download5

**Comment by dark-penguin** [comment]
Did you manage to build it? Could you share a prebuilt wheel for aarch64 or instructions about how to build it?

**Comment by xeffyr** [comment]
> Did you manage to build it

Not. If managed, then of course package would available.

**Comment by dark-penguin** [comment]
I meant this question for @Neo-Oli . From his post, I assumed "please provide a package, because for now I have to build it". Also, I thought pip is supposed to build the package from source if there is no wheel available. So I asked how did he do it.

PyDroid3 developers have managed to build a wheel (they keep it in their "internal" repository), but it's for arm-py36, and we need aarch64-py37. I've managed to set up a 32-bit arm Termux, install that wheel and symlink Python libraries to emulate Python 3.6 . Now if I try to import QtWidgets, it says "library libQt5Widgets.so not found". I do not know where to look for it - it's not in site-packages/PyQt5 . I guess this is actually Qt5, so it should be somewhere in Ministro directory?.. I can't find it.

The same thing happens if I try to run my hello-world.py from PyDroid3 from the terminal. However, it works fine if I run it from the editor. I guess the editor preloads the Ministro libraries?.. I'm stuck at this point.

**Comment by Neo-Oli** [comment]
@dark-penguin Sorry, I also haven't managed to build it.

**Comment by AlexAllu** [comment]
Is there any alternate method to use gui for python in termux???

**Comment by ferroao** [comment]
> Is there any alternate method to use gui for python in termux???

jupyter lab, jupyter notebook

**Comment by Yisus7u7** [comment]
@xeffyr Now that apparently termux has more compatibility with qt5 than with gtk, I think if it might be possible to add the package not?

**Comment by Yisus7u7** [comment]
#361
