### ISSUE TITLE
install inkscape on android

### ISSUE THREAD

**Issue by mahdi1dev** [termux/x11-packages#403]
Welcome
I had root using [termux-sudo](https://gitlab.com/st42/termux-sudo)  previously but when I updated [termux](https://f-droid.org/packages/com.termux/)  it no longer works and I try to install [inkscape](https://inkscape.org)  on android and I can't
Can this problem be solved?
Thank you all.

**Comment by xeffyr** [comment]
We don't have `inkscape` package, so I really don't know what and how you want to install. You even didn't provided the information about actual problems, at least screenshot. Our X11 packages are rootless, you don't need root for installation or use. Moreover, you can't use Termux `apt` with sudo since it is patched against execution under uid 0 (root).

This repository is only about official Termux packages (the X11 set). I will not look into any third-party things, neither solve their issues.
