### ISSUE TITLE
[Bug]: Otter browser not working

### ISSUE THREAD

**Issue by masterjavaofficial** [termux/x11-packages#495]
### Problem description

~ $ otter-browser
CANNOT LINK EXECUTABLE "otter-browser": library "libicuuc.so.69" not found
~ $

### What steps will reproduce the bug?

$ otter-browser

### System information

termux-info:

N/A

**Comment by ONUGOD** [comment]
The problem is that the new version of libicu [libicu 70.1] has problems with the browser.

I take this opportunity to comment some things about my experience with the browser, I saw that they added that it depends on libsqlite to run and it's great.

Although with that the browser can run, at times it will ask you for packages like ffmpeg and gst-plugins-good... Although if we need an "improvement" it would be great that they added the gst-libav package back to the repositories, at least thanks to it we can watch long videos on Youtube because if you try to watch a short one you get an error: [Error: "Secure connection setup failed."] and that one at least I have not been able to fix it.
